-- H2 2.3.232;
SET DB_CLOSE_DELAY -1;        
;             
CREATE USER IF NOT EXISTS "SA" SALT '5dd8eaeca39c4521' HASH '5fcd73a5a1a98fbfa60c57f8ef737a5d37bb26503232fdfcffebbeb51873111f' ADMIN;         
CREATE MEMORY TABLE "PUBLIC"."FORM"(
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 3) NOT NULL,
    "AGREE" BOOLEAN NOT NULL,
    "NAME" CHARACTER VARYING(255)
);           
ALTER TABLE "PUBLIC"."FORM" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_2" PRIMARY KEY("ID");         
-- 2 +/- SELECT COUNT(*) FROM PUBLIC.FORM;    
INSERT INTO "PUBLIC"."FORM" VALUES
(1, TRUE, 'test'),
(2, TRUE, 'test 1');  
CREATE MEMORY TABLE "PUBLIC"."FORM_SECTOR"(
    "FORM_ID" BIGINT NOT NULL,
    "SECTOR_ID" BIGINT NOT NULL
);              
-- 7 +/- SELECT COUNT(*) FROM PUBLIC.FORM_SECTOR;             
INSERT INTO "PUBLIC"."FORM_SECTOR" VALUES
(1, 43),
(1, 342),
(1, 378),
(1, 437),
(2, 91),
(2, 93),
(2, 508);           
CREATE MEMORY TABLE "PUBLIC"."SECTOR"(
    "ID" BIGINT NOT NULL,
    "NAME" CHARACTER VARYING(255),
    "PARENT_ID" BIGINT
);             
ALTER TABLE "PUBLIC"."SECTOR" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_9" PRIMARY KEY("ID");       
-- 79 +/- SELECT COUNT(*) FROM PUBLIC.SECTOR; 
INSERT INTO "PUBLIC"."SECTOR" VALUES
(1, 'Manufacturing', NULL),
(2, 'Service', NULL),
(3, 'Other', NULL),
(5, 'Printing', 1),
(6, 'Food and Beverage', 1),
(7, 'Textile and Clothing', 1),
(8, 'Wood', 1),
(9, 'Plastic and Rubber', 1),
(11, 'Metalworking', 1),
(12, 'Machinery', 1),
(13, 'Furniture', 1),
(18, 'Electronics and Optics', 1),
(19, 'Construction materials', 1),
(21, 'Transport and Logistics', 2),
(22, 'Tourism', 2),
(25, 'Business services', 2),
(28, 'Information Technology and Telecommunications', 2),
(29, 'Energy technology', 3),
(33, 'Environment', 3),
(35, 'Engineering', 2),
(37, 'Creative industries', 3),
(39, 'Milk & dairy products', 6),
(40, 'Meat & meat products', 6),
(42, 'Fish & fish products', 6),
(43, 'Beverages', 6),
(44, 'Clothing', 7),
(45, 'Textile', 7),
(47, 'Wooden houses', 8),
(51, 'Wooden building materials', 8),
(53, 'Plastics welding and processing', 559),
(54, 'Packaging', 9),
(55, 'Blowing', 559),
(57, 'Moulding', 559),
(62, 'Forgings, Fasteners', 542),
(66, 'MIG, TIG, Aluminum welding', 542),
(67, 'Construction of metal structures', 11),
(69, 'Gas, Plasma, Laser cutting', 542),
(75, 'CNC-machining', 542),
(91, 'Machinery equipment/tools', 12),
(93, 'Metal structures', 12),
(94, 'Machinery components', 12),
(97, 'Maritime', 12),
(98, 'Kitchen', 13),
(99, 'Project furniture', 13),
(101, 'Living room', 13),
(111, 'Air', 21),
(112, 'Road', 21),
(113, 'Water', 21),
(114, 'Rail', 21),
(121, 'Software, Hardware', 28),
(122, 'Telecommunications', 28),
(141, 'Translation services', 2),
(145, 'Labelling and packaging printing', 5),
(148, 'Advertising', 5),
(150, 'Book/Periodicals printing', 5),
(224, 'Manufacture of machinery', 12),
(227, 'Repair and maintenance service', 12),
(230, 'Ship repair and conversion', 97),
(263, 'Houses and buildings', 11),
(267, 'Metal products', 11),
(269, 'Boat/Yacht building', 97),
(271, 'Aluminium and steel workboats', 97),
(337, 'Other (Wood)', 8),
(341, 'Outdoor', 13),
(342, 'Bakery & confectionery products', 6),
(378, 'Sweets & snack food', 6),
(385, 'Bedroom', 13),
(389, 'Bathroom/sauna', 13),
(390, U&'Children\2019s room', 13),
(392, 'Office', 13),
(394, 'Other (Furniture)', 13),
(437, 'Other', 6),
(508, 'Other', 12),
(542, 'Metal works', 11),
(556, 'Plastic goods', 9),
(559, 'Plastic processing technology', 9),
(560, 'Plastic profiles', 9),
(576, 'Programming, Consultancy', 28),
(581, 'Data processing, Web portals, E-marketing', 28);         
ALTER TABLE "PUBLIC"."FORM_SECTOR" ADD CONSTRAINT "PUBLIC"."FKE5RI8A4ITT9AI3J0HV511VTT3" FOREIGN KEY("SECTOR_ID") REFERENCES "PUBLIC"."SECTOR"("ID") NOCHECK; 
ALTER TABLE "PUBLIC"."FORM_SECTOR" ADD CONSTRAINT "PUBLIC"."FK6ASUPPU5RC01DSOKL22UDG10Q" FOREIGN KEY("FORM_ID") REFERENCES "PUBLIC"."FORM"("ID") NOCHECK;     
